fix: Fix for more variant
Signed-off-by: underflow101 <ikarus125@gmail.com>

diff --git a/lp b/lp
--- a/lp
+++ b/lp
@@ -2,16 +2,11 @@
 
 LP_CONFIG_RPATH="infra/config"
 LP_COMMAND_RPATH="infra/command"
-LP_PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+LP_PACKAGE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
 function Usage()
 {
-  echo "Usage: $0 [COMMAND] ..."
-  echo "Command:"
-  for file in "$LP_COMMAND_RPATH"/*;
-  do
-    echo "  $(basename "$file")"
-  done
+  echo "Usage: $0 format [DIRECTORY] ..."
 }
 
 function import()
@@ -26,10 +21,17 @@ if [[ -z "${COMMAND}" ]]; then
   exit 255
 fi
 
-COMMAND_FILE="${LP_PROJECT_PATH}/${LP_COMMAND_RPATH}/${COMMAND}"
+LP_PROJECT_PATH=$2; shift
+
+if [[ -z "${LP_PROJECT_PATH}" ]]; then
+  echo "Invalid"
+  exit 255
+fi
+
+COMMAND_FILE="${LP_PACKAGE_PATH}/${LP_COMMAND_RPATH}/${COMMAND}"
 
 if [[ ! -f "${COMMAND_FILE}" ]]; then
-  echo "ERROR: '${COMMAND}' is not supported"
+  echo "ERROR: Use exact directory, or ${COMMAND} is not valid."
   exit 255
 fi
 
